<?php

use Illuminate\Database\Seeder;
use App\Carrera;

class CarrerasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		Carrera::create([
			'cveCarrera'=>'607316',
			'nombreCarrera'=>'CONTADURÍA PÚBLICA',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'511315',
			'nombreCarrera'=>'INGENIERO CONSTRUCTOR',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'521312',
			'nombreCarrera'=>'INGENIERÍA EN SISTEMAS COMPUTACIONALES',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'622306',
			'nombreCarrera'=>'MERCADOTECNIA',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'771302',
			'nombreCarrera'=>'DISEÑO GRÁFICO',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'611310',
			'nombreCarrera'=>'CIENCIAS DE LA COMUNICACIÓN',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'611501',
			'nombreCarrera'=>'ADMINISTRACIÓN PÚBLICA',
			'modalidad'=>'ESCOLARIZADA|SEMIESCOLARIZADA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'612301',
			'nombreCarrera'=>'DERECHO',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'241535',
			'nombreCarrera'=>'EDUCACIÓN ESPECIAL',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'401542',
			'nombreCarrera'=>'ADMINISTRACIÓN EN SISTEMAS DE SALUD',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'621603',
			'nombreCarrera'=>'ADMINISTRACIÓN',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'DOCTORADO',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'244321',
			'nombreCarrera'=>'EDUCACIÓN FÍSICA Y DEPORTE',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'207398',
			'nombreCarrera'=>'CIENCIAS DE LA EDUCACIÓN',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'621560',
			'nombreCarrera'=>'FINANZAS',
			'modalidad'=>'ESCOLARIZADA|MIXTA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'207577',
			'nombreCarrera'=>'ADMINISTRACIÓN EN EDUCACIÓN SUPERIOR',
			'modalidad'=>'ESCOLARIZADA|SEMIESCOLARIZADA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'511301',
			'nombreCarrera'=>'INGENIERÍA CIVIL',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'223371',
			'nombreCarrera'=>'ENSEÑANZA DEL INGLÉS',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'612514',
			'nombreCarrera'=>'DERECHO PENAL',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'612554',
			'nombreCarrera'=>'DERECHO CIVIL',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'611314',
			'nombreCarrera'=>'INFORMÁTICA ADMINISTRATIVA',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'411565',
			'nombreCarrera'=>'CIENCIAS FORENSES',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'622302',
			'nombreCarrera'=>'ECONOMÍA',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'401307',
			'nombreCarrera'=>'MÉDICO',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'612501',
			'nombreCarrera'=>'DERECHO',
			'modalidad'=>'ESCOLARIZADA|SEMIESCOLARIZADA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'515324',
			'nombreCarrera'=>'QUÍMICO FARMACÉUTICO BIÓLOGO',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'511554',
			'nombreCarrera'=>'ADMINISTRACIÓN DE LA CONSTRUCCIÓN',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'311308',
			'nombreCarrera'=>'INGENIERO ZOOTECNISTA ADMINISTRADOR',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'231301',
			'nombreCarrera'=>'PSICOLOGÍA',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'615318',
			'nombreCarrera'=>'GASTRONOMÍA',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'612520',
			'nombreCarrera'=>'DERECHO CONSTITUCIONAL Y AMPARO',
			'modalidad'=>'ESCOLARIZADA|MIXTA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'241603',
			'nombreCarrera'=>'EDUCACIÓN',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'DOCTORADO',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'621549',
			'nombreCarrera'=>'IMPUESTOS',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'411564',
			'nombreCarrera'=>'DOCENCIA EN CIENCIAS DE LA SALUD',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'213551',
			'nombreCarrera'=>'EVALUACIÓN EDUCATIVA',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'612534',
			'nombreCarrera'=>'DERECHO CORPORATIVO',
			'modalidad'=>'ESCOLARIZADA|MIXTA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'612523',
			'nombreCarrera'=>'DERECHO LABORAL',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'431302',
			'nombreCarrera'=>'ENFERMERÍA',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'607502',
			'nombreCarrera'=>'ADMINISTRACIÓN',
			'modalidad'=>'ESCOLARIZADA|SEMIESCOLARIZADA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'624501',
			'nombreCarrera'=>'PUBLICIDAD',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'621303',
			'nombreCarrera'=>'ADMINISTRACIÓN DE EMPRESAS',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'615305',
			'nombreCarrera'=>'ADMINISTRACIÓN DE EMPRESAS TURÍSTICAS',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'421301',
			'nombreCarrera'=>'ODONTOLOGÍA',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'511303',
			'nombreCarrera'=>'ARQUITECTURA',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'611313',
			'nombreCarrera'=>'INFORMÁTICA',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'509577',
			'nombreCarrera'=>'DESARROLLO DE SOFTWARE',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'643319',
			'nombreCarrera'=>'ADMINISTRACIÓN TURÍSTICA Y HOTELERA',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'622335',
			'nombreCarrera'=>'CONTADURÍA PÚBLICA Y ESTRATEGIA FINANCIERA',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'650305',
			'nombreCarrera'=>'ADMINISTRACIÓN Y GESTIÓN DE NEGOCIOS',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'660314',
			'nombreCarrera'=>'GASTRONOMIA Y ENOLOGIA',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'517327',
			'nombreCarrera'=>'INGENIERÍA EN TELECOMUNICACIONES',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'666319',
			'nombreCarrera'=>'MERCADOTECNIA Y COMERCIO ELECTRÓNICO',
			'modalidad'=>'ESCOLARIZADA',
			'nivel'=>'LICENCIATURA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'419611',
			'nombreCarrera'=>'SALUD PÚBLICA Y GESTIÓN SANITARIA',
			'modalidad'=>'MIXTA',
			'nivel'=>'DOCTORADO',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'620529',
			'nombreCarrera'=>'ADMINISTRACIÓN DE REDES Y TELECOMUNICACIONES',
			'modalidad'=>'MIXTA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'642521',
			'nombreCarrera'=>'IMPUESTOS',
			'modalidad'=>'MIXTA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'632584',
			'nombreCarrera'=>'PROCESO PENAL ACUSATORIO',
			'modalidad'=>'MIXTA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
		Carrera::create([
			'cveCarrera'=>'286528',
			'nombreCarrera'=>'TERAPIA FAMILIAR PARA LA ATENCIÓN DE ADICCIONES Y VIOLENCIA',
			'modalidad'=>'MIXTA',
			'nivel'=>'MAESTRÍA',
			'edo'=>1,
			'autorizacion_id'=>1,
			'institucion_id'=>1,
		]);
    }
}
